server:
  port: 8001

dubbo:
  protocol:
    name: dubbo
    serialization: hessian2
    port: -1
  application:
    name: authority-centre
  registry:
    client: curator
    address: zookeeper://192.168.1.93:2181
  scan:
    base-packages: pers.wh.test.dubbo.springboot.provider
  #provider:
    #filter: -exception,cctsException,cuException