server:
  port: 8002

dubbo:
  protocol:
    name: dubbo
    serialization: hessian2
    port: -1
  application:
    name: authority-centre
  registry:
    client: curator
    address: zookeeper://192.168.1.93:2181
  scan:
    base-packages: pers.wh.test.dubbo.springboot.consumer
  provider:
    filter: -exception,cuException,cctsException